# 代币类型，目前支持：eth/etc/rvn/erg/cfx/btc/ltc/scp/ltc
coin_type: "eth"

# 程序本地转发端口
local_addr: ":6688"

# 是否启用客户端 SSL 加密
# 如果内核里边使用 SSL 连接的话，需要设置这个选项为 true
enable_client_ssl: false

# 远程代理地址，常用地址（E池/鱼池/币印等）已经内置 SSL/TCP 判断
remote_addr: "stratum-eth.antpool.com:25"

# 是否启用服务端 SSL 加密
# 大部分常用矿池已经自动进行了判断，无需特殊设置，若设置为 true，则优先级最高
enable_server_ssl: false

# 抽水钱包，请务必自行确认其有效性
wallet: "0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# 开启性能模式：解除 ulimit -n 1024 限制
enable_performance_mode: false

# 开启利润优先模式，默认为 true
# 开启此模式后，会优先保证抽水收益
# 可能会导致抽水比例略微超过设定值
# NOTICE：如果机器频繁掉线，不建议开启
enable_profit_mode: true

# 开启新抽水逻辑，低于 6% 建议使用新逻辑，会让算力曲线更加平稳
# 高抽水比例时，关闭此项可能会提抽水收益
is_experiment_devfee: true

# 抽水矿池地址，默认使用远程代理地址
devfee_addr: "stratum-eth.antpool.com:25"

# 是否启用抽水 SSL 加密
# 大部分常用矿池已经自动进行了判断，无需特殊设置，若设置 true，则优先级最高
enable_devfee_ssl: false

# 抽水比例(支持小数)，最高 100，默认值 0，不抽水
devfee_rate: 2

# 抽水时候指定的 worker 名称
devfee_worker: "TaxCS2"

# 日志输出位置。目前日志是加密存储，格式为 *.xlog
# 如果在程序使用过程中出现异常情况，请将日志提交给开发者进行排查
log_dir: "/tmp"



# DNS 服务器地址：避免 DNS 污染，请使用安全/可访问通的 DNS 地址
# 默认：8.8.8.8, 8.8.4.4
dns_server: "8.8.8.8, 8.8.4.4"

# 临时 block 掉出问题的 IP
# 在使用过程中，发现有些场景下会出现后端可达但是不可使用的场景：
#  DNS 返回的地址，可以访问通，但是无法正常使用）
# 当出现此类场景后，请添加对应 IP 至此
block_ips: ""

# DNS 解析重试次数
# 当通过 dnsServer 解析到对应后端地址后，proxy 会尝试与其建立 TLS/TCP 连接
# 如果 1s 内无法建立成功，则判断当前后端不可达
# 随后将重新向 DNS 发起解析请求
# 默认重试 10 次，超过重试次数后，服务会退出
dns_retry_times: 10

# 加密模式
# 0: 不启用加密，1：客户端（发送加密数据）2：服务端（接收加密数据）
encrypt_mode: 0
